@apiURL=https://fw-teaching.fi/demo/rest/api/v1

### GET products
GET {{apiURL}}/products/

### GET single product
GET {{apiURL}}/products/1003

### POST products
POST {{apiURL}}/products/
Content-Type: application/json

{
    "name": "Jacket", 
    "price": 200
}

### PUT change single product
PUT {{apiURL}}/products/1001
Content-Type: application/json

{
    "name": "Dress-shirt", 
    "price": 70
}

### PATCH update single product
PATCH {{apiURL}}/products/1002
Content-Type: application/json

{
    "price": 35
}

### DELETE single product
DELETE {{apiURL}}/products/1003