@apiURL=http://localhost:8080

# Gammal url
#@apiURL=https://wom24-notess-b9dmaggwa4fqdveu.northeurope-01.azurewebsites.net/

@token={{$dotenv TEMP_TOKEN}}

### Skapa user
POST {{apiURL}}/users/
Content-Type: application/json

{
    "name": "benjamin", 
    "password": "benjamin"
}

### Logga in
POST {{apiURL}}/users/login/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "benjamin", 
    "password": "benjamin"
}

###
GET {{apiURL}}/users/profile
Authorization: Bearer {{token}}